    <!-- </div>
       <div class="container">
        <h2>Alterar Produto</h2>
        <form action="/salvarProduto" method="post">
            <div class="form-group">
                <input type="hidden" class="form-control" id="Id" placeholder="Digite a id" name="id" value="<?php echo $this->view->dados[0]["id"] ?>">
            </div>
            <div class="form-group">
                <label for="nome">Descricao:</label>
                <input type="text" class="form-control" id="Descricao" placeholder="Digite a descricao" name="descricao" value="<?php echo $this->view->dados[0]["descricao"] ?>">
            </div>
            <div class="form-group">
                <label for="email">Preço:</label>
                <input type="text" class="form-control" id="Valor" placeholder="Digite o valor" name="preco" value="<?php echo $this->view->dados[0]["preco"] ?>">
            </div>
           <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div> -->

    <section>
    <div id="telaCadastro">
        <div id="logo">
            <div id="imagem">
                <img src="img/logoSite.png" alt="Help Connect">
            </div>
            <p>Seja Bem-Vindo</p>
        </div>
        <form id="form" action="/salvarCliente" method="POST">
            <div id="container">
                <div style="display:none;"> <!-- DEIXA O ID INVISIVEL PARA O USUARIO -->
                    <p>ID</p>
                    <input type="hiddem" name="id" value="<?php echo $this->view->dados[0]["id"] ?>">
                </div>
                <div id="nome">
                    <p>Nome Produto</p>
                    <input type="text" name="nome" placeholder="Nome" value="<?php echo $this->view->dados[0]["nome"] ?>"/>
                </div>
                <div id="email">
                    <p>Descricao</p>
                    <input type="text" name="email" placeholder="E-mail" value="<?php echo $this->view->dados[0]["email"] ?>"/>
                </div>
                <div id="senha">
                    <p>Preco</p>
                    <input type="text" name="senha" placeholder="Senha" value="<?php echo $this->view->dados[0]["senha"] ?>"/>
                </div>
                <div id="senha">
                    <p>Situação: digite 0 ou 1</p>
                    <input type="number" name="situacao" min="0" max="1" maxlength="1" placeholder="Situacao" value="<?php echo $this->view->dados[0]["situacao"] ?>"/>
                </div>
                <div id="botoes">
                    <div id="cadastro">
                        <button type="submit">Alterar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>
