<section>
    <div id="telaCadastro">
        <div id="logo">
            <div id="imagem">
                <img src="img/logoSite.png" alt="Help Connect">
                <p>Seja Bem-Vindo</p>
            </div>
        </div>
        <form id="form" action="/novoCadastro" method="POST">
            <div id="container">
                <div style="display:none;"> <!-- DEIXA O ID INVISIVEL PARA O USUARIO -->
                    <p>ID</p>
                    <input type="hiddem" name="id" value="0">
                </div>
                <div id="nome">
                    <p>Nome Produto</p>
                    <input type="text" name="nome" placeholder="Nome"/>
                </div>
                <div id="email">
                    <p>Descricao</p>
                    <input type="text" name="email" placeholder="E-mail"/>
                </div>
                <div id="senha">
                    <p>Senha</p>
                    <input type="text" name="senha" placeholder="Senha"/>
                </div>
                <div id="senha">
                    <p>Situação digite 0 ou 1</p>
                    <input type="number" name="situacao" min="0" max="1" maxlength="1" placeholder="Situacao"/>
                </div>
                <div id="botoes">
                    <div id="avancar">
                        <button type="submit">
                            <div id="icon">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
                                    <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                                    <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
                                </svg>
                            </div>
                            <p>Cadastrar-se</p>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>