<section>
    <div id="telaCadastro">
        <div id="logo">
            <div id="imagem">
                <img src="img/logoSite.png" alt="Help Connect">
            </div>
            <p>Seja Bem-Vindo</p>
        </div>
        <form id="form" action="/novoCadastro" method="POST">
            <div id="container">
                <div style="display:none;"> <!-- DEIXA O ID INVISIVEL PARA O USUARIO -->
                    <p>ID</p>
                    <input type="hiddem" name="id" value="0">
                </div>
                <div id="nome">
                    <p>Nome Produto</p>
                    <input type="text" name="nome" placeholder="Nome"/>
                </div>
                <div id="email">
                    <p>Descricao</p>
                    <input type="text" name="email" placeholder="E-mail"/>
                </div>
                <div id="senha">
                    <p>Senha</p>
                    <input type="text" name="senha" placeholder="Senha"/>
                </div>
                <div id="senha">
                    <p>Situação: digite 0 ou 1</p>
                    <input type="number" name="situacao" min="0" max="1" maxlength="1" placeholder="Situacao"/>
                </div>
                <div id="botoes">
                    <div id="cadastro">
                        <button type="submit">Incluir</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>