<!-- <h1> Clientes</h1> 

   <?php
    /*foreach($this->view->dados as $indice => $cliente) {
        echo "<br> " . $cliente["id"] . " - " . $cliente["nome"];
    }*/
    ?> -->

<section>
    <div id="clientes">
        <?php
            foreach($this->view->dados as $indice => $cliente) {
                $tipoPerfil = "";

                if($cliente["situacao"] == 0) {
                    $tipoPerfil = "Comum";

                }else {
                    $tipoPerfil = "Administrativo";

                }

                echo "
                    <div id=\"card\">
                        <div id=\"img\">
                            <svg width=\"1em\" height=\"1em\" viewBox=\"0 0 16 16\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\">
                                <path fill-rule=\"evenodd\" d=\"M1.5 1a.5.5 0 0 0-.5.5v3a.5.5 0 0 1-1 0v-3A1.5 1.5 0 0 1 1.5 0h3a.5.5 0 0 1 0 1h-3zM11 .5a.5.5 0 0 1 .5-.5h3A1.5 1.5 0 0 1 16 1.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 1-.5-.5zM.5 11a.5.5 0 0 1 .5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 1 0 1h-3A1.5 1.5 0 0 1 0 14.5v-3a.5.5 0 0 1 .5-.5zm15 0a.5.5 0 0 1 .5.5v3a1.5 1.5 0 0 1-1.5 1.5h-3a.5.5 0 0 1 0-1h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 1 .5-.5z\"/>
                                <path fill-rule=\"evenodd\" d=\"M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z\"/>
                            </svg>
                        </div>

                        <button class=\"collapsible\">". $cliente["nome"] ."</button>
                        <div class=\"content\">
                            <div id=\"produto\">
                                <p><b>E-mail:</b> "
                                . $cliente["email"] .
                                "</p>
                                <p><b>Senha:</b> "
                                    . $cliente["senha"] .
                                "</p>
                                <p><b>Conta:</b> "
                                    . $tipoPerfil .
                                "</p>
                            </div>
                            <div id=\"opcoes\">
                                <div id=\"botoes\">
                                    <div id=\"comprar\">
                                        <a href='/alterarCliente?id=" . $cliente["id"] . "'>
                                            <div id=\"icon\">
                                                <svg width=\"1em\" height=\"1em\" viewBox=\"0 0 16 16\" class=\"bi bi-pencil-square\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\">
                                                    <path d=\"M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z\"/>
                                                    <path fill-rule=\"evenodd\" d=\"M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z\"/>
                                                </svg>
                                            </div>
                                            <p>Alterar</p>
                                        </a>
                                    </div>
                                </div>
                                <div id=\"botoes\">
                                    <div id=\"comprar\">
                                        <a href='/excluirCliente?id=" . $cliente["id"] . "'>
                                            <div id=\"icon\">
                                                <svg width=\"1em\" height=\"1em\" viewBox=\"0 0 16 16\" class=\"bi bi-x\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\">
                                                    <path fill-rule=\"evenodd\" d=\"M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z\"/>
                                                </svg>
                                            </div>
                                            <p>Excluir</p>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                ";
            }

            echo "
                <div id=\"card\">
                    <div id=\"incluir\">
                        <div id=\"opcoes\">
                            <div id=\"botoes\">
                                <div id=\"comprar\">
                                    <a href='/incluirCliente'>
                                        <div id=\"icon\">
                                            <svg width=\"1em\" height=\"1em\" viewBox=\"0 0 16 16\" class=\"bi bi-plus-circle\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\">
                                                <path fill-rule=\"evenodd\" d=\"M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z\"/>
                                                <path fill-rule=\"evenodd\" d=\"M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z\"/>
                                            </svg>
                                        </div>
                                        <p>Adicionar Usuario</p>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            ";
        ?>
    </div>
</section>