<form id="form" action="/validaLogin" method="POST">
    <div id="container">
        <div id="email">
            <p>E-mail</p>
            <input type="email" name="email" placeholder="E-mail" />
        </div>
        <div id="senha">
            <p>Senha</p>
            <input type="password" name="senha" placeholder="" />
        </div>
        <div id="botoes">
            <div id="acessar">
                <button type="submit">Acessar</button>
                
            </div>
            <div id="cadastro">
                <button><a href="cadastro.php">Cadastrar-se</a></button>
                
            </div>
        </div>
    </div>
</form>