<!-- <h1>Acesso</h1>
<hr />
    <a href="/menuPrincipal">Acesso</a>
<br> -->


<section>
    <div id="conteudo">
        <div id="apresentacao">
            <h1>Desenvolvimento Front end</h1>
            <p>Realizamos o desenvolvimento de seu site, com base em suas ideias. Entre em contato e faca uma contacao conosto.</p>
            <div id="botao">
                <a href="#">
                    <div id="button">Saiba Mais</div>
                </a>
            </div>
        </div>
        <div id="img">
            <img src="img/imgservices.png">
        </div>
    </div>
</section>

<section>
    <div id="produtos">
        <?php
            foreach($this->view->dados as $indice => $produto) {
                echo "
                    <div id=\"card\">
                        <div id=\"img\">
                            <img src=\"img/". $produto["img"] ."\">
                        </div>

                        <button class=\"collapsible\">Saiba Mais</button>
                        <div class=\"content\">
                            <div id=\"produto\">
                                <h1 id=\"h1\">"
                                    . $produto["nome"] .
                                "</h1>
                                <p id=\"p\">"
                                    . $produto["descricao"] .
                                "</p>
                                <h2 id=\"h2\">R$ "
                                    . $produto["preco"] .
                                "</h2>
                            </div>
                        </div>
                    </div>
                ";
            }
        ?>
    </div>
</section>