    <!-- <div class="container">
        <h2>Adicionar Produto</h2>
        <form action="/salvarProduto" method="post">
        	<input type="hidden" class="form-control" id="Id" placeholder="Digite a id" name="id" value="0">
            
            <div class="form-group">
                <label for="nome">Descricao:</label>
                <input type="text" class="form-control" id="Descricao" placeholder="Digite a descricao" name="descricao">
            </div>
            <div class="form-group">
                <label for="email">Preço:</label>
                <input type="text" class="form-control" id="Valor" placeholder="Digite o valor" name="preco">
            </div>
           <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div> -->


<!-- <section>
    <div id="form">
        <form action="/salvarProduto" method="post">
        	<input type="hidden" id="Id" placeholder="Digite a id" name="id" value="0">
            <div id="bloco">
                <label for="nome">Nome:</label>
                <input type="text" placeholder="Nome" name="nome">
            </div>
            <div id="bloco">
                <label for="descricao">Descricao:</label>
                <input type="text" placeholder="Descricao do Produto" name="descricao">
            </div>
            <div id="bloco">
                <label for="preco">Preço:</label>
                <input type="text" placeholder="Valor" name="preco">
            </div>
           <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div>
</section> -->

<section>
    <div id="telaCadastro">
        <div id="logo">
            <div id="imagem">
                <img src="img/logoSite.png" alt="Help Connect">
                <p>Seja Bem-Vindo</p>
            </div>
        </div>
        <form id="form" action="/salvarProduto" method="POST">
            <div id="container">
                <div style="display:none;"> <!-- DEIXA O ID INVISIVEL PARA O USUARIO -->
                    <p>ID</p>
                    <input type="hiddem" name="id" value="0">
                </div>
                <div id="nome">
                    <p>Nome Produto</p>
                    <input type="text" name="nome" placeholder="Nome"/>
                </div>
                <div id="email">
                    <p>Descricao</p>
                    <input type="text" name="descricao" placeholder="Descricao"/>
                </div>
                <div id="senha">
                    <p>Preco</p>
                    <input type="text" name="preco" placeholder="Preco"/>
                </div>
                <div id="img">
                    <p>Imagem</p>
                    <input type="file" name="img" placeholder="Preco"/>
                </div>
                <div id="botoes">
                    <div id="avancar">
                        <button type="submit">
                            <div id="icon">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cart4" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                                </svg>
                            </div>
                            <p>Incluir</p>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section>

