	<!--<div class="container">
    <h2>
      <a href='/incluirProduto'>
        <img src="imagens/usuarios.png" alt="Incluir Usuarios" width="45" height="45">
      </a>
      Lista dos produtos cadastrados no sistema
    </h2>
    <br>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Ações</th>
          <th>Id</th>
          <th>Descrição</th>
          <th>Preço</th>
        </tr>
      </thead>
      <tbody>
        <?php
       	/*    foreach($this->view->dados as $indice => $produto) {
            echo "<tr><td>
                  <a href='/alterarProduto?id=" . $produto["id"] . "'>
                      <img src='imagens/pen-icon.png' alt='Alterar' width='25' height='25'>
                  </a>

                  <a href='/excluirProduto?id=" . $produto["id"] . "'>
                      <img src='imagens/Button-Delete-icon.png' alt='Alterar' width='25' height='25'>
                  </a>
                  
                  </td><td>"
              . $produto["id"] .
              "</td><td>"
              . $produto["descricao"] .
              "</td><td>"
              . $produto["preco"] .
              "</td></tr>";
          }
        */?>
      </tbody>
    </table>
  </div>-->

<section>
    <div id="produtos">
        <?php
            foreach($this->view->dados as $indice => $produto) {
                echo "
                    <div id=\"card\">
                        <div id=\"img\">
                            <div id=\"opcoes\">
                                <a href='/alterarProduto?id=" . $produto["id"] . "'>
                                    <svg width=\"1em\" height=\"1em\" viewBox=\"0 0 16 16\" class=\"bi bi-pencil-square\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\">
                                        <path d=\"M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z\"/>
                                        <path fill-rule=\"evenodd\" d=\"M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z\"/>
                                    </svg>
                                </a>
                                <a href='/excluirProduto?id=" . $produto["id"] . "'>
                                    <svg width=\"1em\" height=\"1em\" viewBox=\"0 0 16 16\" class=\"bi bi-x\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\">
                                        <path fill-rule=\"evenodd\" d=\"M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z\"/>
                                    </svg>
                                </a>
                            </div>
                            <img src=\"img/layout_teste.jpg\">
                        </div>

                        <div id=\"produto\">
                            <h1>"
                                . $produto["nome"] .
                            "</h1>
                        </div>

                        <div id=\"produto\">
                            <p>"
                                . $produto["descricao"] .
                            "</p>
                        </div>

                        <div id=\"produto\">
                            <h2>R$ "
                                . $produto["preco"] .
                            "</h2>
                        </div>
                    </div>
                ";
            }

            echo "
                <div id=\"card\">
                    <div id=\"img\">
                        <a href='/incluirProduto'>
                            <img src=\"img/include.png\">
                        </a>
                    </div>
                </div>
            ";
        ?>
    </div>
</section>
